name: Concatener 
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      
      - name: gitconf
        run: git config --global user.name "Antoine Morvant"
      - name: git show
        run: git config user.name
      - name: git conf
        run: git config --global user.email "antoine.morvant@hotmail.fr"
      - name: git c
        run: git checkout main
      - name: git c
        run: git pull origin main
      - name : copier
        run: cat indices/indice* > in.md
      - name: check for changes
        run:  git status
      - name: stage changed files
        run:  
              git add in.md
              
      - name: commit changed files
        run: 
            git commit -m "Auto updating"
      - name: fetch from master
        run: git fetch origin main
      - name: push vers main
              
        run: git push origin main
   
       
