name: Concatener 
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name : copier
        run: cat indices/indice* > in.md
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add in
      - name: commit changed files
        run: git commit -m "Auto updating"
      - name: fetch from master
        run: git fetch origin master
      - name: push code to master
        run: git push origin HEAD:master
   
       
