name: CréerZip 
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      
      - name: gitconf
        run: git config --global user.name "Antoine Morvant"
      - name: montrer mon nom pour checker
        run: git config user.name
      - name: git conf
        run: git config --global user.email "antoine.morvant@hotmail.fr"
      - name: git check
        run: git checkout main
      - name: git pull
        run: git pull origin main
      - name : zip
        run: zip -r indices.zip indices/ 
      - name: status
        run:  git status
      - name: add
        run:  
              git add indices.md
              
      - name: commit
        run: 
            git commit -m "Auto updating"
      - name: fetch from master
        run: git fetch origin main
      - name: push vers main
              
        run: git push origin main
